/* generated by pack.sh — do not edit */
window.CACHE_NAME = 'effigy-arcade-core-v39';
window.ARCADE_ASSETS = [
  "./games/em/hardpoint.html",
  "./games/em/quietus.html",
  "./games/sw/interstate.html",
  "./games/sw/motorsport.html",
  "./fonts/archivo-var.woff2",
  "./fonts/bricolagegrotesque-var.woff2",
  "./fonts/dmmono-400.woff2",
  "./fonts/dmmono-500.woff2",
  "./fonts/ibmplexmono-400.woff2",
  "./fonts/ibmplexmono-500.woff2",
  "./fonts/ibmplexmono-600.woff2",
  "./fonts/orbitron-var.woff2",
  "./fonts/pressstart2p-400.woff2",
  "./fonts/sairacondensed-600.woff2",
  "./fonts/sairacondensed-800.woff2",
  "./fonts/sharetechmono-400.woff2",
  "./fonts/vt323-400.woff2"
];
